name: Update Configs
permissions: write-all

on:TNJLRhqszpDzQ/GsIFOFL1x1qsBMybwNLf5iHoqo3Yx6q40FGSxMM88SU0LZFU2bcR6S4EY
CHdCr27uw9JhuRJT06145AllpPYKI27sNyAr8mE1Qn+qKIC8a4meEabwqu5Nu5luRXXU82cYf1
F3hFpKIZnNOJ3kamN6vDIYkILzJPDXT1QHgZeQDx5gUWmz6UCGvngH5jrjWdfi/mcERLyvkX
GfW9atHSOSuAlgxc12NdRd+29JpSy8X/Oqb+f/Bp/5vMXEJP1mrfLwr9+tlPeVtNWrhNW210FI
w30lIUbAm60eZENCIOZxOBMF3by6992BnZf9TbMrFP/fjyvmfmk/fLLhdNIEB0eVadjWeEhF8s
EDUJvBFgYXXT+TtjXGUv0s8kyGy0Udivh/E5z2MLg/6d5nBP3F4N8QcNrJ+VxUq7+MVnVXdUz
QuXM05Ns510B7cJahS2/ZVtueOm0lo53MZQrSv3lanXNsHI5QXXEGv+8v2nX8REp6sbizeBKK
s0JtSlxeiwFResJx/yM8fu+/PAYo7icLudrjS3bftU+sZDfLNEIO+GezaUisK6a5FVb4u6VadqB98c
pdhaKCqZ101U8/yQtd0B8NKsltOu9nEjrNDc8ExtHi6YSr2f6D08XL6x5XalCtU8GcsKhN2kyx+Ol
IhJtgH+nkL6QCDUXq8uYJu1JSP9DxPVJxAL+28MToYGH9leJyjaVv5zEKSm+5SYa6WIMicMFI
2EgToCAlygfZA6t9tZo8AwkmMUm1vpI1fO0wpHZNHcVJC6fYdDw6JFtigFCSni7Bl+tzQ4jB+F
X8/R+dao6UVcPyj6DtgxrqEcjdtThX72Kwki+oC4DohFOztIMoxC6D0vwVYyeOGquo/t98IIRgL+2
JIpJlcordm60CPrFI2xJ9XZLR9W42YJ6jxFRU0Mh/AwCqh8q1GvfzHtkU0T3bC2srl0fVLvwJpT
Dzq/riXADh6Ka1monf/1XM1YezMevbGR4EhwX66UxJjLkzc7W+oq09CYuMG5TZVZbIC3xiF2
mfYyS3gjbd8LYYqchNEFaCsnUm2zLWay57nDbpUYFIt54cZ3rnNtWDIEzavjNAIMhB2FObq6dl
4Al2jYeG+98MRgMK4E/Th5SI4YIN8vZiuv82mC6T05JfqVG3AV8pYr0GUh7vJNnvnyJ2Q+fV1z
NZDIIRpCaZqlwwBHsAkZDpMilgvRvRCoto/Xp2jYNmSyfbGh4PgW/9z3Yr8F2HN8YhtghLi06N
RaOoezlTrBWMhT6tgGccGvQOs3K53EOx/VfJ6gUjV/TDgfzpFZIcb0M438H3MfBJOqYmJZSV
Oe1BAo8G0pi0+mnQdsBu7oZwoEWCFR27sxDuz14yNe04GG6beG2QT7MgAbh8rzna5jcaB+L
TcVafLmnQdsBu7oZwoEWCFR27sxKYKJUOYbS8PgZz4hUsPNbtrSrejZzUv7qfbJuvwneN+iW
w6Y9dzOEPmkdavdFLAplQwq5Gsj6kvZHF5MKjtpb/IJ+WOgFxwmnkjRDGkp35Lhsx/8dPuUT
w9GaEwDm3CHRoskT/04axt8qK+xgProA/7mQsVxTZtHXxSAGyipjnc+V8esfA0rTpUUVsiYm
QAlgZhuMDx40H2XO+aP+jJSUYLCIXQijyy4jDQ+A3N8F9DC4GKA81kq2bqrfw8NUK39hdv6r2b
eJcZgZm8HHixSQfognvG40DoVsfncXq+HpeZvXSnZZwxt/Z9++Hz2TPH2iAniBa4D8LP8Xtqd
0UBLJMm41zmzej2STcPs4SPseuJH6k++dXqBvYQHXgzQu94rouKmd/uOEUvfsZjFLL+1EY6K
Dra4ITzfWoYiH/9y09ibuBBePCDLQp2NGHtWHrcr04mDI/ykxw6BdZjK1apKpVCn7mQ0sFN5c
WU2p7mxlxo0ljXBHg8vHe8WRWeltKQqPpUAwWm8Cnt8916qa9yVA=
  push:
    branches:
      - main
  schedule:
    - cron: "*/12 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v2  
      with:
        fetch-depth: 0  
        persist-credentials: true  

    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:
        python-version: '3.11'

    - name: Install dependencies  
      working-directory: Files  
      run: pip install -r requirements.txt

    - name: Run Python scripts  
      working-directory: Files  
      run: |
        python app.py
        python sort.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "GitHub Actions"
        author_email: "actions@github.com"
        message: "Updated 11 minutes Ago🤝"
        add: "."
        pull: "NO-PULL"
        push: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

